/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema;
import java.awt.Image;
import java.sql.*;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HALION
 */
public class login extends javax.swing.JFrame {
    //
    String x = "";
    String y = "";
    //
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setTitle("Login");
        this.setSize(400,400);
        Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagen/senatiIcon.png"));
        lblLogo.setIcon(new ImageIcon(img.getScaledInstance(lblLogo.getWidth(),lblLogo.getHeight(),Image.SCALE_SMOOTH)));
        this.setIconImage(img);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("usuario");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel2.setText("contraseña");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\HALION\\Documents\\senatiIcon.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 3, 24)); // NOI18N
        jLabel4.setText("SENATI´S MEAT SHOP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String usuario = txtUser.getText();
        String pass = txtClave.getText();
        
        if(pass.isEmpty() || usuario.isEmpty()){
            JOptionPane.showMessageDialog(null,"Ambos campos son obligatorios");  
        }else{
            
            conexion.conexion();
        }
            conexion.conexion();
            try{
                String query = "SELECT * FROM empleado WHERE DNI_EMP='"+usuario+"'and CONT_EMP='"+pass+"'";
                Statement st = conexion.conexion().createStatement();
                ResultSet rs = st.executeQuery(query);
            int encontrado = rs.getRow();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Login Exitoso");
                this.x = txtClave.getText();
                this.y = txtUser.getText();
                
                
                Condicionales(st);
                hide();
                conexion.v2.setVisible(true);
            }else{
                txtUser.setText("");
                txtClave.setText("");
                JOptionPane.showMessageDialog(null, "usuario o contraseña incorrecta");
            }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }

    }//GEN-LAST:event_btnIngresarActionPerformed
    void Condicionales(Statement st) throws SQLException {
        int cargo = 0;
        String query2 = "SELECT COD_CARGO FROM empleado WHERE DNI_EMP='"+this.y+"' AND CONT_EMP='"+this.x+"'";
        ResultSet rs2 = st.executeQuery(query2);
        while(rs2.next()){
        cargo = rs2.getInt("COD_CARGO");
        }
        switch (cargo) {
            case 1:
                conexion.v2.HabilitarAlmacen();
                conexion.v2.HabilitarCompra();
                conexion.v2.DeshabilitarDelivery();
                conexion.v2.HabilitarEmpleados();
                conexion.v2.HabilitarUbicacion();
                conexion.v2.DeshabilitarVenta();
                break;
            case 2:
                conexion.v2.DeshabilitarEmpleados();
                conexion.v2.DeshabilitarAlmacen();
                conexion.v2.DeshabilitarCompra();
                conexion.v2.DeshabilitarDelivery();
                conexion.v2.HabilitarUbicacion();
                conexion.v2.DeshabilitarVenta();
                break;
            case 3:
                conexion.v2.DeshabilitarCompra();
                conexion.v2.DeshabilitarUbicacion();
                conexion.v2.DeshabilitarDelivery();
                conexion.v2.DeshabilitarEmpleados();
                conexion.v2.DeshabilitarVenta();
                conexion.v2.HabilitarAlmacen();
                break;
            case 4:
                conexion.v2.DeshabilitarAlmacen();
                conexion.v2.DeshabilitarCompra();
                conexion.v2.DeshabilitarEmpleados();
                conexion.v2.DeshabilitarUbicacion();
                conexion.v2.DeshabilitarDelivery();
                conexion.v2.DeshabilitarVenta();
                break;
            case 5:
                conexion.v2.DeshabilitarAlmacen();
                conexion.v2.DeshabilitarCompra();
                conexion.v2.DeshabilitarEmpleados();
                conexion.v2.DeshabilitarDelivery();
                conexion.v2.DeshabilitarUbicacion();
                conexion.v2.DeshabilitarVenta();
                break;
            default:
                break;
        }
    }
    //    
    public String getContra(){  
        
        return x;
        }
    
     public String getDNI(){
        return y;
    }
    //
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
