/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.*;
/**
 *
 * @author HALION
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        
        Image imgEmp = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagen/iconempleados2.png"));
        btnEmp.setIcon(new ImageIcon(imgEmp.getScaledInstance(btnEmp.getWidth(),btnEmp.getHeight(),Image.SCALE_SMOOTH)));
        this.setIconImage(imgEmp);
        this.setLocationRelativeTo(null);
        
        Image img2 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagen/iconalmacen2.png"));
        btnAlmacen.setIcon(new ImageIcon(img2.getScaledInstance(btnAlmacen.getWidth(),btnAlmacen.getHeight(),Image.SCALE_DEFAULT)));
        this.setIconImage(img2);
        this.setLocationRelativeTo(null);
        
        Image img3 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagen/iconVenta2.png"));
        btnVenta.setIcon(new ImageIcon(img3.getScaledInstance(btnVenta.getWidth(),btnVenta.getHeight(),Image.SCALE_DEFAULT)));
        this.setIconImage(img3);
        this.setLocationRelativeTo(null);
        
        Image img4 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagen/iconDelivery2.png"));
        btnDelivery.setIcon(new ImageIcon(img4.getScaledInstance(btnDelivery.getWidth(),btnDelivery.getHeight(),Image.SCALE_DEFAULT)));
        this.setIconImage(img4);
        this.setLocationRelativeTo(null);
        
        Image img5 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagen/iconCompra2.png"));
        btnCompra.setIcon(new ImageIcon(img5.getScaledInstance(btnCompra.getWidth(),btnCompra.getHeight(),Image.SCALE_DEFAULT)));
        this.setIconImage(img5);
        this.setLocationRelativeTo(null);
        
        Image img6 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagen/iconUbicacion2.png"));
        btnUbi.setIcon(new ImageIcon(img6.getScaledInstance(btnUbi.getWidth(),btnUbi.getHeight(),Image.SCALE_DEFAULT)));
        this.setIconImage(img6);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btnAlmacen = new javax.swing.JButton();
        btnEmp = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnUbi = new javax.swing.JButton();
        btnDelivery = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVenta.setText("Venta");
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        btnAlmacen.setText("Almacen");
        btnAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenActionPerformed(evt);
            }
        });

        btnEmp.setText("Empleados");
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });

        btnCompra.setText("Compra");
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnUbi.setText("Ubicacion");
        btnUbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbiActionPerformed(evt);
            }
        });

        btnDelivery.setText("Devilery");
        btnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryActionPerformed(evt);
            }
        });

        jButton8.setText("Cambiar Contraseña");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUbi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Sesion Cerrada Correctamente");
        conexion.v1.setVisible(true);
        hide();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void HabilitarVenta(){
        btnVenta.setEnabled(true);
    }
    public void DeshabilitarVenta(){
        btnVenta.setEnabled(false);
    }
    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        hide();
        conexion.v4.setVisible(true);
    }//GEN-LAST:event_btnVentaActionPerformed
        public void HabilitarAlmacen(){
        btnAlmacen.setEnabled(true);
    }
    public void DeshabilitarAlmacen(){
        btnAlmacen.setEnabled(false);
    }
    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenActionPerformed
        hide();
        conexion.v8.setVisible(true);
        
    }//GEN-LAST:event_btnAlmacenActionPerformed
    public void HabilitarDelivery(){
        btnDelivery.setEnabled(true);
    }
    public void DeshabilitarDelivery(){
        btnDelivery.setEnabled(false);
    }
    private void btnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryActionPerformed
         hide();
        conexion.v6.setVisible(true);
       
    }//GEN-LAST:event_btnDeliveryActionPerformed
    public void HabilitarEmpleados(){
        btnEmp.setEnabled(true);
    }
    public void DeshabilitarEmpleados(){
        btnEmp.setEnabled(false);
    }
    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
          hide();
        conexion.v9.setVisible(true);
      
        
    }//GEN-LAST:event_btnEmpActionPerformed
    public void HabilitarCompra(){
        btnCompra.setEnabled(true);
    }
    public void DeshabilitarCompra(){
        btnCompra.setEnabled(false);
    }
    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
          hide();
        conexion.v7.setVisible(true);
      
    }//GEN-LAST:event_btnCompraActionPerformed
    public void HabilitarUbicacion(){
        btnUbi.setEnabled(true);
    }
    public void DeshabilitarUbicacion(){
        btnUbi.setEnabled(false);
    }
    private void btnUbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbiActionPerformed
         hide();
        conexion.v5.setVisible(true);
       
    }//GEN-LAST:event_btnUbiActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        hide();
        conexion.v3.setVisible(true);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlmacen;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnDelivery;
    private javax.swing.JButton btnEmp;
    private javax.swing.JButton btnUbi;
    private javax.swing.JButton btnVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables
}
